apiVersion: v1
kind: Secret
metadata:
  name: foo
data:
  count: NQ==
  sleep: MQ==
---
apiVersion: v1
kind: Pod
metadata:
    name: secret
spec:
  containers:
    - command:
        - secret
      name: container
      image: hello:latest
      env:
        - name: COUNT
          valueFrom:
            secretKeyRef:
              key: count
              name: foo
        - name: SLEEP
          valueFrom:
            secretKeyRef:
              key: sleep
              name: foo
  restartPolicy: Never